# Sheldon plugin manager configuration
# Docs: https://sheldon.cli.rs

shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"
rev = "53a26e287fbbe2dcebb3aa1801546c6de32416fa"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
tag = "v0.7.1"
apply = ["defer"]

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"
tag = "v1.1.0"
apply = ["defer"]

[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
tag = "v1.56"
apply = ["defer"]

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"
